---
name: Build and publish a 🛢️ container

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  schedule:
    - cron: "0 8,16 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push-container:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - label: x86_64
            platform: amd64
            runner: ubuntu-24.04
          - label: AArch64
            platform: arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Source checkout
        uses: actions/checkout@v7

      - name: Build Vox Pupuli renovate container
        uses: voxpupuli/gha-build-and-publish-a-container@v2
        with:
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          build_arch: linux/${{ matrix.platform }}
          buildfile: Containerfile
          docker_username: voxpupulibot
          docker_password: ${{ secrets.DOCKERHUB_BOT_ADMIN_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/renovate:${{ github.sha }}-${{ matrix.platform }}

  create-multiarch-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build-and-push-container
    steps:
      - name: Log in to the ghcr.io registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the docker.io registry
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: voxpupulibot
          password: ${{ secrets.DOCKERHUB_BOT_ADMIN_TOKEN }}

      - name: Create multiarch manifests
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/renovate:latest \
            ghcr.io/${{ github.repository_owner }}/renovate:${{ github.sha }}-arm64 \
            ghcr.io/${{ github.repository_owner }}/renovate:${{ github.sha }}-amd64

          docker buildx imagetools create -t docker.io/${{ github.repository_owner }}/renovate:latest \
            ghcr.io/${{ github.repository_owner }}/renovate:${{ github.sha }}-arm64 \
            ghcr.io/${{ github.repository_owner }}/renovate:${{ github.sha }}-amd64

  update-dockerhub-description:
    runs-on: ubuntu-latest
    needs:
      - create-multiarch-manifests
    steps:
      - name: Source checkout
        uses: actions/checkout@v7

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: voxpupulibot
          password: ${{ secrets.DOCKERHUB_BOT_ADMIN_TOKEN }}
          repository: voxpupuli/renovate
